kind: pipeline
type: docker
name: build-and-publish

volumes:
  - name: build-folder
    temp: {}

steps:
  - name: npm
    image: plugins/npm
    settings:
      username:
        from_secret:
          npm_username
      password:
        from_secret:
          npm_password
      email:
        from_secret:
          npm_email
