kind: pipeline
type: docker
name: build-and-publish

volumes:
  - name: build-folder
    temp: {}

steps:
  - name: build
    image: node:13.12.0-alpine
    volumes:
      - name: build-folder
        path: /build
    commands:
      - npm i
      - echo "Building app"
  - name: publish
    image: plugins/npm
    settings:
      username:
        from_secret:
          npm_username
      password:
        from_secret:
          npm_password
      email:
        from_secret:
          npm_email
      token:
        from_secret:
          npm_token
